[package]
name = "boxcars-py"
version = "0.1.0"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"

[dependencies]
pyo3 = { version = "0.8.5", features = ["extension-module"] }

[lib]
name = "boxcars_py"
crate-type = ["cdylib"]
